export const Routes = {
  Splash: 'Splash',
  Quiz: 'Quiz',
  Home: 'Home',
  EditAlarm: 'EditAlarm',
  ChooseMission: 'ChooseMission',
  AlarmSound: 'AlarmSound',
  SoundLibrary: 'SoundLibrary',
  Insights: 'Insights',
  DailyReports: 'DailyReports',
  Groups: 'Groups',
  GroupDetail: 'GroupDetail',
  Settings: 'Settings',
  TrackSleep: 'TrackSleep',
  AlarmRinging: 'AlarmRinging',
  CameraMission: 'CameraMission',
  ShakeMission: 'ShakeMission',
  PushupMission: 'PushupMission',
  MathMission: 'MathMission',
  ReadAloudMission: 'ReadAloudMission',
  MissionSuccess: 'MissionSuccess',
} as const;
